export const REGISTER_YAP_ERRORS = {
  tooShort: 'Too Short!',
  tooLong: 'Too Long!',
  onlyLatinLetters: 'Only Latin letters are allowed',
  required: 'Required',
  passportSchema: 'Schema: AB1234567',
  passportInvalid: 'Invalid passport',
  invalidPhoneNumber: 'Invalid phone number',
  ageLimits: 'Something went wrong',
  confirmRules: 'Rules must be confirmed',
  passwordLength: 'Minimum length is 12',
  passwordMessage: 'Only Latin letters, at least 1 digit, at least 1 UpperCase letter',
  repeatPassword: 'Passwords don\'t match',
  onlyNumbers: 'only numbers',
  incorrectEmail: 'incorrect email',
  enterCorrectValue: 'enter correct value',
};
